// SPDX-License-Identifier: CC0-1.0

//! Generate the per-version blocking facade.
//!
//! The facade exposes the *sync* client's exact method surface and routes every call through the
//! async production client on a private current-thread runtime. Crucially it does not define a
//! second surface: it reuses the very same `impl_client_*` macros the sync client is built from,
//! read straight out of `client_sync/v{N}/mod.rs`. So the curated surface has one source of truth
//! (the sync client), the facade tracks it per version for free, and there is nothing to
//! hand-maintain. The unchanged integration tests run against the async transport because
//! `bitcoind` swaps `node.client` to this type under its `client-async` feature.
//!
//! One method is the exception: `getnewaddress` is routed through the GENERATED async wrapper (see
//! [`BRIDGE_GET_NEW_ADDRESS`]) instead of the reused sync macro, so its argument encoding does not
//! come from the sync client. That isolates the async path: a bug planted in the sync
//! `getnewaddress` arg-encoding (an acceptance test for isolation) fails the sync client but leaves
//! this async-backed facade green.

/// The `getnewaddress` isolation bridge: reproduces the sync macro's four public methods, but the
/// low-level call goes through the generated async wrapper (`inner.get_new_address_with`) instead of
/// `self.call("getnewaddress", ...)`, so the sync client's argument encoding (and any bug in it)
/// never reaches the async path. `{version}` is the only placeholder; it is filled in by
/// [`emit_blocking`]. The sync `get_new_address` macro is skipped (see [`extract_macro_surface`]).
const BRIDGE_GET_NEW_ADDRESS: &str = r#"// Isolation bridge: `getnewaddress` goes through the GENERATED async wrapper (its own argument
// encoding), NOT the reused sync macro. A bug planted in the sync `getnewaddress` arg-encoding
// therefore fails the sync client but not this async-backed facade.
impl Client {
    /// `getnewaddress` via the generated async wrapper, returning the generated raw type.
    fn get_new_address_generated(
        &self,
        label: Option<&str>,
        ty: Option<AddressType>,
    ) -> Result<crate::types::v{version}::generated::GetNewAddress> {
        let address_type = match ty {
            Some(ty) => Some(serde_json::from_value::<String>(into_json(ty)?)?),
            None => None,
        };
        let opts = crate::client_async::v{version}::wallet::GetNewAddressOptions {
            label: label.map(str::to_owned),
            address_type,
        };
        self.rt.block_on(self.inner.get_new_address_with(opts)).map_err(Self::map_err)
    }

    /// Low-level `getnewaddress` (matches the sync client's signature).
    pub fn get_new_address(
        &self,
        label: Option<&str>,
        ty: Option<AddressType>,
    ) -> Result<crate::types::v{version}::generated::GetNewAddress> {
        self.get_new_address_generated(label, ty)
    }

    /// Gets a new address and parses it assuming it is correct.
    pub fn new_address(&self) -> Result<bitcoin::Address> {
        let model = self.get_new_address_generated(None, None)?.into_model().unwrap();
        Ok(model.0.assume_checked())
    }

    /// Gets a new address of the given type and parses it assuming it is correct.
    pub fn new_address_with_type(&self, ty: AddressType) -> Result<bitcoin::Address> {
        let model = self.get_new_address_generated(None, Some(ty))?.into_model().unwrap();
        Ok(model.0.assume_checked())
    }

    /// Gets a new address with a label and parses it assuming it is correct (unchecked network).
    pub fn new_address_with_label(
        &self,
        label: &str,
    ) -> Result<bitcoin::Address<bitcoin::address::NetworkUnchecked>> {
        let model = self.get_new_address_generated(Some(label), None)?.into_model().unwrap();
        Ok(model.0)
    }
}

"#;

/// Emit `blocking.rs` for `version`, reusing the sync client's macro surface taken from
/// `sync_mod_src` (the verbatim contents of `client_sync/v{N}/mod.rs`).
pub(crate) fn emit_blocking(version: &str, sync_mod_src: &str) -> String {
    let reexports = extract_reexport_block(sync_mod_src);
    let macros = extract_macro_surface(sync_mod_src);
    // `getnewaddress` routes through the generated async wrapper, not the reused sync macro, so a bug
    // in the sync arg-encoding cannot leak into the async client. `{version}` is its only placeholder.
    let bridge = BRIDGE_GET_NEW_ADDRESS.replace("{version}", version);

    format!(
        "// SPDX-License-Identifier: CC0-1.0\n\n\
         //! Auto-generated blocking facade for Bitcoin Core `{version}`.\n//!\n\
         //! Generated by `codegen`. Do not edit by hand, re-run `just codegen` to regenerate.\n//!\n\
         //! Exposes the same method surface as the sync client `crate::client_sync::v{version}` by\n\
         //! reusing the very same `impl_client_*` macros, but each call is routed through the async\n\
         //! production client ([`crate::client_async::Client`]) on a private current-thread runtime.\n\
         //! `bitcoind` swaps `node.client` to this type under its `client-async` feature, so the\n\
         //! unchanged integration tests exercise the async transport.\n\n\
         #![allow(unused_imports, clippy::needless_pass_by_value, clippy::too_many_arguments)]\n\n\
         use std::collections::BTreeMap;\n\
         use std::fmt;\n\
         use std::path::Path;\n\n\
         use bitcoin::address::{{Address, NetworkChecked}};\n\
         use bitcoin::{{sign_message, Amount, Block, BlockHash, PublicKey, Txid}};\n\
         use serde::de::DeserializeOwned;\n\
         use serde::Serialize;\n\
         use serde_json::{{json, Value}};\n\n\
         use crate::client_async::{{Auth as AsyncAuth, Builder}};\n\
         use crate::client_sync::error::Error;\n\
         use crate::client_sync::{{Auth, Result}};\n\
         use crate::types::v{version}::*;\n\n\
         {reexports}\n\n\
         /// Shorthand for `serde_json::to_value`, matching the free `into_json` the reused sync\n\
         /// `impl_client_*` macros call.\n\
         fn into_json<T: Serialize>(val: T) -> Result<Value> {{ Ok(serde_json::to_value(val)?) }}\n\n\
         /// The version-specific response-type namespace the integration tests import under\n\
         /// `test-async`. Mirrors `crate::types::v{version}` (the curated types the facade's macro\n\
         /// methods return) so `bitcoind::vtype` resolves the same names whether `node.client` is\n\
         /// the sync client or this facade.\n\
         pub mod vtype {{\n    \
             pub use crate::types::v{version}::*;\n\
         }}\n\n\
         /// A blocking JSON-RPC client that drives the async `v{version}` production client.\n\
         pub struct Client {{\n    \
             inner: crate::client_async::Client,\n    \
             rt: tokio::runtime::Runtime,\n\
         }}\n\n\
         impl fmt::Debug for Client {{\n    \
             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {{\n        \
                 write!(f, \"corepc_client::client_async::blocking::Client({{:?}})\", self.inner)\n    \
             }}\n\
         }}\n\n\
         impl Client {{\n    \
             /// Creates a blocking async-backed client (signature matches `client_sync`'s `new_with_auth`).\n    \
             pub fn new_with_auth(url: &str, auth: Auth) -> Result<Self> {{\n        \
                 let auth = match auth {{\n            \
                     Auth::None => AsyncAuth::None,\n            \
                     Auth::UserPass(user, pass) => AsyncAuth::UserPass(user, pass),\n            \
                     Auth::CookieFile(path) => AsyncAuth::CookieFile(path),\n        \
                 }};\n        \
                 let inner = Builder::new()\n            \
                     .url(url)\n            \
                     .map_err(|e| Error::Returned(e.to_string()))?\n            \
                     .auth(auth)\n            \
                     // Match the sync client's transport timeout: the integration suite runs many\n            \
                     // nodes in parallel and slow setup calls are calibrated against that value.\n            \
                     .timeout(std::time::Duration::from_secs(60))\n            \
                     .build()\n            \
                     .map_err(|e| Error::Returned(e.to_string()))?;\n        \
                 let rt = tokio::runtime::Builder::new_current_thread()\n            \
                     .enable_all()\n            \
                     .build()\n            \
                     .map_err(|e| Error::Returned(e.to_string()))?;\n        \
                 Ok(Self {{ inner, rt }})\n    \
             }}\n\n    \
             /// Maps an async-client error into the sync error type used by the tests. A JSON-RPC\n    \
             /// application error keeps its code and message so callers that inspect Core error\n    \
             /// codes behave the same against either client.\n    \
             fn map_err(e: crate::client_async::Error) -> Error {{\n        \
                 match e {{\n            \
                     crate::client_async::Error::Rpc {{ code, message, .. }} =>\n                \
                         Error::JsonRpc(jsonrpc::error::Error::Rpc(jsonrpc::error::RpcError {{\n                    \
                             code,\n                    \
                             message,\n                    \
                             data: None,\n                \
                         }})),\n            \
                     other => Error::Returned(other.to_string()),\n        \
                 }}\n    \
             }}\n\n    \
             /// Call an RPC `method` with the given `args`. The single primitive every\n    \
             /// `impl_client_*` macro is built on; here it blocks on the async client's `call_raw`.\n    \
             pub fn call<T: DeserializeOwned>(&self, method: &str, args: &[Value]) -> Result<T> {{\n        \
                 self.rt.block_on(self.inner.call_raw(method, args)).map_err(Self::map_err)\n    \
             }}\n\
         }}\n\n\
         {bridge}\
         {macros}\n"
    )
}

/// Reproduce the `pub use crate::client_sync::{{ ... }};` re-export block from the sync `mod.rs`.
///
/// These are the request helper types (`Input`, `Output`, `AddressType`, ...) that the reused
/// macros name in their signatures, so the facade needs the identical set in scope.
fn extract_reexport_block(src: &str) -> String {
    let mut out = Vec::new();
    let mut in_block = false;
    for line in src.lines() {
        if line.trim_start().starts_with("pub use crate::client_sync::{") {
            in_block = true;
            out.push("#[rustfmt::skip]".to_owned());
            out.push(line.to_owned());
            continue;
        }
        if in_block {
            out.push(line.to_owned());
            if line.trim() == "};" {
                break;
            }
        }
    }
    out.join("\n")
}

/// Pull the ordered macro surface (section comments + `crate::impl_client_*!()` invocations) out of
/// the sync `mod.rs`, dropping `define_jsonrpc_bitreq_client!` (the facade defines its own client).
fn extract_macro_surface(src: &str) -> String {
    let mut out = Vec::new();
    for line in src.lines() {
        let t = line.trim_start();
        if t.starts_with("// ==") {
            out.push(String::new());
            out.push(line.to_owned());
        } else if t.starts_with("crate::impl_client_") {
            // `get_new_address` is bridged to the generated async wrapper (see
            // `BRIDGE_GET_NEW_ADDRESS`); drop the sync macro to avoid a duplicate definition.
            if t.contains("__get_new_address!") {
                out.push("// get_new_address: bridged to the generated async wrapper (see above)."
                    .to_owned());
                continue;
            }
            out.push(line.to_owned());
        }
    }
    out.join("\n").trim_start().to_owned()
}
