// SPDX-License-Identifier: CC0-1.0

//! Generate the per-version blocking facade.
//!
//! The facade exposes the *sync* client's exact method surface and routes every call through the
//! async production client on a private current-thread runtime. It does not define a second surface:
//! it reuses the very same `impl_client_*` macros the sync client is built from, read straight out
//! of `client_sync/v{N}/mod.rs`. So the curated surface has one source of truth (the sync client),
//! the facade tracks it per version for free, and there is nothing to hand-maintain. The unchanged
//! integration tests run against the async transport because `bitcoind` swaps `node.client` to this
//! type under its `client-async` feature.
//!
//! The method surface itself comes from the `impl_async_bridges!` macro in
//! `client_async/blocking_bridges.rs` (real Rust, not a string template here): every method routes
//! through the generated async wrappers, so a bug in the sync arg-encoding cannot reach the async
//! path. The generated file just invokes `crate::impl_async_bridges!(v{N});` plus the version-check
//! macro kept from the sync `mod.rs` ([`KEPT_MACROS`]).


/// Emit `blocking.rs` for `version`, reusing the sync client's macro surface taken from
/// `sync_mod_src` (the verbatim contents of `client_sync/v{N}/mod.rs`).
pub(crate) fn emit_blocking(version: &str, sync_mod_src: &str) -> String {
    let reexports = extract_reexport_block(sync_mod_src);
    let macros = extract_macro_surface(sync_mod_src);

    format!(
        "// SPDX-License-Identifier: CC0-1.0\n\n\
         //! Auto-generated blocking facade for Bitcoin Core `{version}`.\n//!\n\
         //! Generated by `codegen`. Do not edit by hand, re-run `just codegen` to regenerate.\n//!\n\
         //! Exposes the same method surface as the sync client `crate::client_sync::v{version}` by\n\
         //! reusing the very same `impl_client_*` macros, but each call is routed through the async\n\
         //! production client ([`crate::client_async::Client`]) on a private current-thread runtime.\n\
         //! `bitcoind` swaps `node.client` to this type under its `client-async` feature, so the\n\
         //! unchanged integration tests exercise the async transport. Methods listed in the codegen\n\
         //! the codegen `KEPT_MACROS` are provided by `crate::impl_async_bridges!` instead (see below).\n\n\
         #![allow(unused_imports, clippy::needless_pass_by_value, clippy::too_many_arguments)]\n\n\
         use std::collections::BTreeMap;\n\
         use std::fmt;\n\
         use std::path::Path;\n\n\
         use bitcoin::address::{{Address, NetworkChecked}};\n\
         use bitcoin::{{sign_message, Amount, Block, BlockHash, PublicKey, Txid}};\n\
         use serde::de::DeserializeOwned;\n\
         use serde::Serialize;\n\
         use serde_json::{{json, Value}};\n\n\
         use crate::client_async::{{Auth as AsyncAuth, Builder}};\n\
         use crate::client_sync::error::Error;\n\
         use crate::client_sync::{{Auth, Result}};\n\
         use crate::types::v{version}::*;\n\n\
         {reexports}\n\n\
         /// Shorthand for `serde_json::to_value`, matching the free `into_json` the reused sync\n\
         /// `impl_client_*` macros call.\n\
         fn into_json<T: Serialize>(val: T) -> Result<Value> {{ Ok(serde_json::to_value(val)?) }}\n\n\
         /// The version-specific response-type namespace the integration tests import under\n\
         /// `test-async`. GENERATED types only: every response type (and its `into_model` error)\n\
         /// comes from `crate::types::v{version}::generated`, so every test `into_model()` runs the\n\
         /// generated conversion. Explicit aliases map union-variant / verbose-level names onto the\n\
         /// names the tests use (an explicit `pub use` shadows the glob). The trailing curated\n\
         /// imports are the few types with NO generated counterpart (RPCs absent from the OpenRPC\n\
         /// spec, or response shapes the tests read raw without `into_model`).\n\
         pub mod vtype {{\n    \
             pub use crate::types::v{version}::generated::*;\n\n    \
             // Union-variant and verbose-level aliases onto the names the tests use.\n    \
             #[rustfmt::skip]\n    \
             pub use crate::types::v{version}::generated::{{\n        \
                 GetBlockTemplateVariant2 as GetBlockTemplate,\n        \
                 GetTxOutVariant1 as GetTxOut,\n        \
                 GetPeerInfoItem as PeerInfo,\n        \
                 GetMempoolFeeRateDiagram as GetMempoolFeerateDiagram,\n        \
                 ScanTxOutSetVariant0 as ScanTxOutSetStart,\n        \
                 ScanBlocksVariant1 as ScanBlocksStart,\n        \
                 GetBlockVerbose0 as GetBlockVerboseZero,\n        \
                 GetBlockVerbose1 as GetBlockVerboseOne,\n        \
                 GetBlockVerbose2 as GetBlockVerboseTwo,\n        \
                 GetBlockVerbose3 as GetBlockVerboseThree,\n        \
                 GetBlockHeaderVerbose0 as GetBlockHeader,\n        \
                 GetBlockHeaderVerbose1 as GetBlockHeaderVerbose,\n        \
                 GetMempoolAncestorsVerbose0 as GetMempoolAncestors,\n        \
                 GetMempoolAncestorsVerbose1 as GetMempoolAncestorsVerbose,\n        \
                 GetMempoolDescendantsVerbose0 as GetMempoolDescendants,\n        \
                 GetMempoolDescendantsVerbose1 as GetMempoolDescendantsVerbose,\n        \
                 GetRawMempoolVerbose0 as GetRawMempool,\n        \
                 GetRawMempoolVerbose1 as GetRawMempoolVerbose,\n        \
                 GetRawMempoolVerbose2 as GetRawMempoolSequence,\n        \
                 GetRawTransactionVerbose0 as GetRawTransaction,\n        \
                 GetRawTransactionVerbose1 as GetRawTransactionVerbose,\n        \
                 SendManyVerbose0 as SendMany,\n        \
                 SendManyVerbose1 as SendManyVerbose,\n        \
                 SendToAddressVerbose0 as SendToAddress,\n        \
                 SendResult as Send,\n        \
                 SignRawTransactionWithWallet as SignRawTransaction,\n        \
                 GetChainTipsError as ChainTipsError,\n        \
                 GetMempoolEntryError as MempoolEntryError,\n        \
                 ScanTxOutSetStartError as ScanTxOutSetError,\n        \
                 GetOrphanTxsVerbose0 as GetOrphanTxs,\n        \
                 GetOrphanTxsVerbose1 as GetOrphanTxsVerboseOne,\n        \
                 GetOrphanTxsVerbose2 as GetOrphanTxsVerboseTwo,\n        \
                 GetOrphanTxsVerboseOneError as GetOrphanTxsVerboseOneEntryError,\n        \
                 GetOrphanTxsVerboseTwoError as GetOrphanTxsVerboseTwoEntryError,\n        \
                 EstimateRawFeeLongFail as RawFeeRange,\n    \
             }};\n\n    \
             // Curated types with no generated counterpart: hidden/no-spec RPC responses and\n    \
             // shapes the tests read raw (no `into_model`). `Logging` shadows the generated one\n    \
             // (the generated response is a plain map; tests read named bool fields).\n    \
             #[rustfmt::skip]\n    \
             pub use crate::types::v{version}::{{\n        \
                 Logging, GetZmqNotifications, ScanBlocksStatus, ScanBlocksAbort,\n        \
                 TransactionCategory,\n        \
                 ScanTxOutSetStatus, ScanTxOutSetAbort,\n    \

                 }};\n    \

             pub use crate::types::v17::GetMemoryInfoStats;\n    \
             pub use crate::types::NumericError;\n\
         }}\n\n\
         /// A blocking JSON-RPC client that drives the async `v{version}` production client.\n\
         pub struct Client {{\n    \
             inner: crate::client_async::Client,\n    \
             rt: tokio::runtime::Runtime,\n\
         }}\n\n\
         impl fmt::Debug for Client {{\n    \
             fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {{\n        \
                 write!(f, \"corepc_client::client_async::blocking::Client({{:?}})\", self.inner)\n    \
             }}\n\
         }}\n\n\
         impl Client {{\n    \
             /// Creates a blocking async-backed client (signature matches `client_sync`'s `new_with_auth`).\n    \
             pub fn new_with_auth(url: &str, auth: Auth) -> Result<Self> {{\n        \
                 let auth = match auth {{\n            \
                     Auth::None => AsyncAuth::None,\n            \
                     Auth::UserPass(user, pass) => AsyncAuth::UserPass(user, pass),\n            \
                     Auth::CookieFile(path) => AsyncAuth::CookieFile(path),\n        \
                 }};\n        \
                 let inner = Builder::new()\n            \
                     .url(url)\n            \
                     .map_err(|e| Error::Returned(e.to_string()))?\n            \
                     .auth(auth)\n            \
                     // Match the sync client's transport timeout: the integration suite runs many\n            \
                     // nodes in parallel and slow setup calls are calibrated against that value.\n            \
                     .timeout(std::time::Duration::from_secs(60))\n            \
                     .build()\n            \
                     .map_err(|e| Error::Returned(e.to_string()))?;\n        \
                 let rt = tokio::runtime::Builder::new_current_thread()\n            \
                     .enable_all()\n            \
                     .build()\n            \
                     .map_err(|e| Error::Returned(e.to_string()))?;\n        \
                 Ok(Self {{ inner, rt }})\n    \
             }}\n\n    \
             /// Maps an async-client error into the sync error type used by the tests. A JSON-RPC\n    \
             /// application error keeps its code and message so callers that inspect Core error\n    \
             /// codes behave the same against either client.\n    \
             fn map_err(e: crate::client_async::Error) -> Error {{\n        \
                 match e {{\n            \
                     crate::client_async::Error::Rpc {{ code, message, .. }} =>\n                \
                         Error::JsonRpc(jsonrpc::error::Error::Rpc(jsonrpc::error::RpcError {{\n                    \
                             code,\n                    \
                             message,\n                    \
                             data: None,\n                \
                         }})),\n            \
                     other => Error::Returned(other.to_string()),\n        \
                 }}\n    \
             }}\n\n    \
             /// Call an RPC `method` with the given `args`. The single primitive every\n    \
             /// `impl_client_*` macro is built on; here it blocks on the async client's `call_raw`.\n    \
             pub fn call<T: DeserializeOwned>(&self, method: &str, args: &[Value]) -> Result<T> {{\n        \
                 self.rt.block_on(self.inner.call_raw(method, args)).map_err(Self::map_err)\n    \
             }}\n\
         }}\n\n\
         // Isolation bridges: methods the facade owns instead of reusing the sync macros (see\n\
         // `client_async/blocking_bridges.rs`).\n\
         crate::impl_async_bridges!(v{version});\n\n\
         {macros}\n"
    )
}

/// Reproduce the `pub use crate::client_sync::{{ ... }};` re-export block from the sync `mod.rs`.
///
/// These are the request helper types (`Input`, `Output`, `AddressType`, ...) that the reused
/// macros name in their signatures, so the facade needs the identical set in scope.
fn extract_reexport_block(src: &str) -> String {
    let mut out = Vec::new();
    let mut in_block = false;
    for line in src.lines() {
        if line.trim_start().starts_with("pub use crate::client_sync::{") {
            in_block = true;
            out.push("#[rustfmt::skip]".to_owned());
            out.push(line.to_owned());
            continue;
        }
        if in_block {
            out.push(line.to_owned());
            if line.trim() == "};" {
                break;
            }
        }
    }
    out.join("\n")
}

/// Pull the ordered macro surface (section comments + `crate::impl_client_*!()` invocations) out of
/// the sync `mod.rs`, dropping `define_jsonrpc_bitreq_client!` (the facade defines its own client)
/// keeping only [`KEPT_MACROS`] (the facade provides everything else via `impl_async_bridges!`).
fn extract_macro_surface(src: &str) -> String {
    let mut out = Vec::new();
    for line in src.lines() {
        let t = line.trim_start();
        // `impl_async_bridges!` implements the whole method surface; the only sync macro the
        // facade reuses is the version-check one (its expected-versions argument lives in the
        // sync `mod.rs`). Everything else would be a duplicate definition. Matching on the
        // KEPT_MACROS prefix also survives the sync mod being commented out wholesale.
        if KEPT_MACROS.iter().any(|k| t.trim_start_matches("// ").starts_with(k)) {
            out.push(line.trim_start().trim_start_matches("// ").to_owned());
        }
    }
    out.join("\n").trim_start().to_owned()
}

/// Sync macro invocations the facade reuses verbatim (see `extract_macro_surface`).
const KEPT_MACROS: &[&str] = &["crate::impl_client_check_expected_server_version!"];

/// Error-name aliases for the sync build's `vtype` shim: the integration tests annotate
/// `into_model` results with the GENERATED error names; under the sync client the curated
/// conversions return these (mostly bare foreign) error types instead. `(name, target path)`.
const SYNC_ERROR_ALIASES: &[(&str, &str)] = &[
    ("DeriveAddressesError", "bitcoin::address::ParseError"),
    ("EstimateSmartFeeError", "bitcoin::amount::ParseAmountError"),
    ("GenerateToAddressError", "bitcoin::hex::HexToArrayError"),
    ("GenerateToDescriptorError", "bitcoin::hex::HexToArrayError"),
    ("GetAddressesByLabelError", "bitcoin::address::ParseError"),
    ("GetBalanceError", "bitcoin::amount::ParseAmountError"),
    ("GetBestBlockHashError", "bitcoin::hex::HexToArrayError"),
    ("GetBlockHashError", "bitcoin::hex::HexToArrayError"),
    ("GetBlockVerboseZeroError", "bitcoin::consensus::encode::FromHexError"),
    ("GetMempoolAncestorsError", "bitcoin::hex::HexToArrayError"),
    ("GetMempoolAncestorsVerboseError", "MapMempoolEntryError"),
    ("GetMempoolDescendantsError", "bitcoin::hex::HexToArrayError"),
    ("GetMempoolDescendantsVerboseError", "MapMempoolEntryError"),
    ("GetPrioritisedTransactionsError", "bitcoin::hex::HexToArrayError"),
    ("GetRawChangeAddressError", "bitcoin::address::ParseError"),
    ("GetRawMempoolError", "bitcoin::hex::HexToArrayError"),
    ("GetRawMempoolSequenceError", "bitcoin::hex::HexToArrayError"),
    ("GetRawMempoolVerboseError", "MapMempoolEntryError"),
    ("GetReceivedByAddressError", "bitcoin::amount::ParseAmountError"),
    ("GetReceivedByLabelError", "bitcoin::amount::ParseAmountError"),
    ("ListLockUnspentError", "ListLockUnspentItemError"),
    ("ListTransactionsError", "TransactionItemError"),
    ("ListUnspentError", "ListUnspentItemError"),
    ("RescanBlockchainError", "crate::NumericError"),
    ("SendManyError", "bitcoin::hex::HexToArrayError"),
    ("SendManyVerboseError", "bitcoin::hex::HexToArrayError"),
    ("SendToAddressError", "bitcoin::hex::HexToArrayError"),
    ("SignMessageError", "bitcoin::sign_message::MessageSignatureError"),
    ("SignMessageWithPrivKeyError", "bitcoin::sign_message::MessageSignatureError"),
    ("SimulateRawTransactionError", "bitcoin::amount::ParseAmountError"),
    ("VerifyTxOutProofError", "bitcoin::hex::HexToArrayError"),
    ("WalletDisplayAddressError", "bitcoin::address::ParseError"),
    ("CreatePsbtError", "bitcoin::psbt::PsbtParseError"),
    ("CombinePsbtError", "bitcoin::psbt::PsbtParseError"),
    ("CombineRawTransactionError", "bitcoin::consensus::encode::FromHexError"),
    ("ConvertToPsbtError", "bitcoin::psbt::PsbtParseError"),
    ("DecodeRawTransactionError", "RawTransactionError"),
    ("GetRawTransactionError", "bitcoin::consensus::encode::FromHexError"),
    ("JoinPsbtsError", "bitcoin::psbt::PsbtParseError"),
    ("UtxoUpdatePsbtError", "bitcoin::psbt::PsbtParseError"),
    ("CreateRawTransactionError", "bitcoin::consensus::encode::FromHexError"),
    ("SendRawTransactionError", "bitcoin::hex::HexToArrayError"),
    ("GetPrivateBroadcastInfoError", "bitcoin::consensus::encode::FromHexError"),
];

/// Emit `types/src/v{N}/generated/vtype_sync.rs`: the response-type namespace the SYNC build's
/// `bitcoind::vtype` points at. Curated types plus error-name aliases, so test annotations
/// written against the generated error names compile against the curated conversions too.
pub(crate) fn emit_vtype_sync(version: &str) -> String {
    let mut s = format!(
        "// SPDX-License-Identifier: CC0-1.0\n\n\
         //! Auto-generated `vtype` shim for the SYNC build of Bitcoin Core `{version}`.\n//!\n\
         //! Generated by `codegen`. Do not edit by hand, re-run `just codegen` to regenerate.\n//!\n\
         //! `bitcoind` re-exports this module as `vtype` when the `client-async` feature is off,\n\
         //! so the integration tests resolve response types to the CURATED types (the sync\n\
         //! client's surface). The `type` aliases map the GENERATED error names the tests\n\
         //! annotate onto the (mostly bare foreign) error types the curated conversions return.\n\n\
         pub use crate::v{version}::*;\n\n"
    );
    for (name, target) in SYNC_ERROR_ALIASES {
        s.push_str(&format!("pub type {name} = {target};\n"));
    }
    s
}
