// SPDX-License-Identifier: CC0-1.0

//! Auto-generated blocking facade for Bitcoin Core `31`.
//!
//! Generated by `codegen`. Do not edit by hand, re-run `just codegen` to regenerate.
//!
//! Exposes the same method surface as the sync client `crate::client_sync::v31` by
//! reusing the very same `impl_client_*` macros, but each call is routed through the async
//! production client ([`crate::client_async::Client`]) on a private current-thread runtime.
//! `bitcoind` swaps `node.client` to this type under its `client-async` feature, so the
//! unchanged integration tests exercise the async transport. Methods listed in the codegen
//! `BRIDGED_METHODS` are provided by `crate::impl_async_bridges!` instead (see below).

#![allow(unused_imports, clippy::needless_pass_by_value, clippy::too_many_arguments)]

use std::collections::BTreeMap;
use std::fmt;
use std::path::Path;

use bitcoin::address::{Address, NetworkChecked};
use bitcoin::{sign_message, Amount, Block, BlockHash, PublicKey, Txid};
use serde::de::DeserializeOwned;
use serde::Serialize;
use serde_json::{json, Value};

use crate::client_async::{Auth as AsyncAuth, Builder};
use crate::client_sync::error::Error;
use crate::client_sync::{Auth, Result};
use crate::types::v31::*;

#[rustfmt::skip]
pub use crate::client_sync::{
    v17::{
      AddNodeCommand, ImportMultiRequest, ImportMultiScriptPubKey, ImportMultiTimestamp, Input, Output, SetBanCommand, WalletCreateFundedPsbtInput,
      FeeEstimateMode,
    },
    v21::ImportDescriptorsRequest,
    v23::AddressType,
    v29::{TemplateRequest, TemplateRules}
};

/// Shorthand for `serde_json::to_value`, matching the free `into_json` the reused sync
/// `impl_client_*` macros call.
fn into_json<T: Serialize>(val: T) -> Result<Value> { Ok(serde_json::to_value(val)?) }

/// The version-specific response-type namespace the integration tests import under
/// `test-async`. GENERATED types only: every response type (and its `into_model` error)
/// comes from `crate::types::v31::generated`, so every test `into_model()` runs the
/// generated conversion. Explicit aliases map union-variant / verbose-level names onto the
/// names the tests use (an explicit `pub use` shadows the glob). The trailing curated
/// imports are the few types with NO generated counterpart (RPCs absent from the OpenRPC
/// spec, or response shapes the tests read raw without `into_model`).
pub mod vtype {
    pub use crate::types::v31::generated::*;

    // Union-variant and verbose-level aliases onto the names the tests use.
    #[rustfmt::skip]
    pub use crate::types::v31::generated::{
        GetBlockTemplateVariant2 as GetBlockTemplate,
        GetTxOutVariant1 as GetTxOut,
        GetPeerInfoItem as PeerInfo,
        GetMempoolFeeRateDiagram as GetMempoolFeerateDiagram,
        ScanTxOutSetVariant0 as ScanTxOutSetStart,
        ScanBlocksVariant1 as ScanBlocksStart,
        GetBlockVerbose0 as GetBlockVerboseZero,
        GetBlockVerbose1 as GetBlockVerboseOne,
        GetBlockVerbose2 as GetBlockVerboseTwo,
        GetBlockVerbose3 as GetBlockVerboseThree,
        GetBlockHeaderVerbose0 as GetBlockHeader,
        GetBlockHeaderVerbose1 as GetBlockHeaderVerbose,
        GetMempoolAncestorsVerbose0 as GetMempoolAncestors,
        GetMempoolAncestorsVerbose1 as GetMempoolAncestorsVerbose,
        GetMempoolDescendantsVerbose0 as GetMempoolDescendants,
        GetMempoolDescendantsVerbose1 as GetMempoolDescendantsVerbose,
        GetRawMempool as GetRawMempoolVerbose,
        GetRawMempool as GetRawMempoolSequence,
        GetRawTransactionVerbose0 as GetRawTransaction,
        GetRawTransactionVerbose1 as GetRawTransactionVerbose,
        SendManyVerbose0 as SendMany,
        SendManyVerbose1 as SendManyVerbose,
        SendToAddressVerbose0 as SendToAddress,
        SendResult as Send,
        SignRawTransactionWithWallet as SignRawTransaction,
        GetChainTipsError as ChainTipsError,
        GetMempoolEntryError as MempoolEntryError,
        ScanTxOutSetStartError as ScanTxOutSetError,
    };

    // Curated types with no generated counterpart: hidden/no-spec RPC responses and
    // shapes the tests read raw (no `into_model`). `Logging` shadows the generated one
    // (the generated response is a plain map; tests read named bool fields).
    #[rustfmt::skip]
    pub use crate::types::v31::{
        Logging, GetZmqNotifications, ScanBlocksStatus, ScanBlocksAbort,
        TransactionCategory,
        ScanTxOutSetStatus, ScanTxOutSetAbort, AddPeerAddress,
    };
    pub use crate::types::v17::GetMemoryInfoStats;
    pub use crate::types::NumericError;
}

/// A blocking JSON-RPC client that drives the async `v31` production client.
pub struct Client {
    inner: crate::client_async::Client,
    rt: tokio::runtime::Runtime,
}

impl fmt::Debug for Client {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "corepc_client::client_async::blocking::Client({:?})", self.inner)
    }
}

impl Client {
    /// Creates a blocking async-backed client (signature matches `client_sync`'s `new_with_auth`).
    pub fn new_with_auth(url: &str, auth: Auth) -> Result<Self> {
        let auth = match auth {
            Auth::None => AsyncAuth::None,
            Auth::UserPass(user, pass) => AsyncAuth::UserPass(user, pass),
            Auth::CookieFile(path) => AsyncAuth::CookieFile(path),
        };
        let inner = Builder::new()
            .url(url)
            .map_err(|e| Error::Returned(e.to_string()))?
            .auth(auth)
            // Match the sync client's transport timeout: the integration suite runs many
            // nodes in parallel and slow setup calls are calibrated against that value.
            .timeout(std::time::Duration::from_secs(60))
            .build()
            .map_err(|e| Error::Returned(e.to_string()))?;
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| Error::Returned(e.to_string()))?;
        Ok(Self { inner, rt })
    }

    /// Maps an async-client error into the sync error type used by the tests. A JSON-RPC
    /// application error keeps its code and message so callers that inspect Core error
    /// codes behave the same against either client.
    fn map_err(e: crate::client_async::Error) -> Error {
        match e {
            crate::client_async::Error::Rpc { code, message, .. } =>
                Error::JsonRpc(jsonrpc::error::Error::Rpc(jsonrpc::error::RpcError {
                    code,
                    message,
                    data: None,
                })),
            other => Error::Returned(other.to_string()),
        }
    }

    /// Call an RPC `method` with the given `args`. The single primitive every
    /// `impl_client_*` macro is built on; here it blocks on the async client's `call_raw`.
    pub fn call<T: DeserializeOwned>(&self, method: &str, args: &[Value]) -> Result<T> {
        self.rt.block_on(self.inner.call_raw(method, args)).map_err(Self::map_err)
    }
}

// Isolation bridges: methods the facade owns instead of reusing the sync macros (see
// `client_async/blocking_bridges.rs`).
crate::impl_async_bridges!(v31);

crate::impl_client_check_expected_server_version!({ [310000] });

// == Network ==
// get_network_info: bridged by `impl_async_bridges!` (see above).
// get_node_addresses: bridged by `impl_async_bridges!` (see above).
// get_peer_info: bridged by `impl_async_bridges!` (see above).
// list_banned: bridged by `impl_async_bridges!` (see above).
// ping: bridged by `impl_async_bridges!` (see above).
