--- # rust-bitcoin CI: If you edit this file please update README.md
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - "test-ci/**"
  pull_request:

name: Continuous integration

jobs:
  Stable: # 2 jobs, one per lock file.
    name: Test - stable toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dep: [minimal, recent]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Run stable tests"
        run: cargo rbmt --lock-file ${{ matrix.dep }} test --toolchain stable

  Nightly: # 2 jobs, one per lock file.
    name: Test - nightly toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dep: [minimal, recent]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Run nightly tests"
        run: cargo rbmt --lock-file ${{ matrix.dep }} test --toolchain nightly

  MSRV: # 2 jobs, one per lock file.
    name: Test - 1.75.0 toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dep: [minimal, recent]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Run MSRV tests"
        run: cargo rbmt --lock-file ${{ matrix.dep }} test --toolchain msrv

  Lint:
    name: Lint - nightly toolchain
    runs-on: ubuntu-latest
    env:
      BITCOIND_SKIP_DOWNLOAD: "1"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Run lints"
        run: |
          cargo rbmt --lock-file recent lint
          ./contrib/lint-integration-tests.sh
          ./contrib/lint-verify.sh

  Docs:
    name: Docs - stable toolchain
    runs-on: ubuntu-latest
    env:
      BITCOIND_SKIP_DOWNLOAD: "1"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Run doc tests"
        run: cargo rbmt --lock-file recent docs

  Docsrs:
    name: Docs - nightly toolchain
    runs-on: ubuntu-latest
    env:
      BITCOIND_SKIP_DOWNLOAD: "1"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Run docsrs tests"
        run: cargo rbmt --lock-file recent docsrs

  Format: #  1 job, run cargo rbmt fmt directly.
    name: Format - nightly toolchain
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Check formatting"
        run: |
          cargo rbmt fmt --check
          ./contrib/fmt-integration-tests.sh
          ./contrib/fmt-verify.sh

  Verify: #  1 job, run `verify` directly.
    name: Verify - stable toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@stable
      - name: "Run the verify program"
        # Verify all versions (known to the verify program)
        run: cd verify && cargo run all

  Integration: # 1 job for each bitcoind version we support.
    name: Integration tests - stable toolchain
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@6560b728ae6a81af9d92713b630ba26772fbd970 # v0.1.0
      - name: "Cache downloaded bitcoind"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.cache/corepc/bitcoind
          key: bitcoind-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Cargo.toml') }}
      - name: "Run integration tests"
        env:
          BITCOIND_DOWNLOAD_DIR: ${{ github.workspace }}/.cache/corepc/bitcoind
        run: cargo rbmt integration
